apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':coupon-domain')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA는 coupon-domain에 있으므로 제거
    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.3'
}