apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':coupon-domain')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA (coupon-domain의 Repository/Entity 직접 사용)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // Swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.3'
}