plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

group = 'eCommerce'
version = '0.0.1-SNAPSHOT'

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.4.3"
        }
    }

    dependencies {
        compileOnly("org.projectlombok:lombok")
        annotationProcessor("org.projectlombok:lombok")
        testImplementation("org.springframework.boot:spring-boot-starter-test")
        testRuntimeOnly("org.junit.platform:junit-platform-launcher")
        testImplementation 'io.projectreactor:reactor-test'
        testImplementation 'com.h2database:h2'
            // Spring Boot Actuator (메트릭 엔드포인트 제공)
            implementation 'org.springframework.boot:spring-boot-starter-actuator'

            // Micrometer Prometheus 레지스트리 (Prometheus 포맷으로 메트릭 노출)
            implementation 'io.micrometer:micrometer-registry-prometheus'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
