spring:
  application:
    name: coupon-api
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abcd
    password: '1234'
    hikari:
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380
      lettuce:
        pool:
          max-active: 50    # 최대 커넥션 수
          max-idle: 20      # 유휴 커넥션 유지
          min-idle: 5       # 최소 유휴 커넥션
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081
  netty:
    connection-timeout: 10s
    max-keep-alive-requests: 10000

springdoc:
  swagger-ui:
    path: /swagger-ui.html